"""
Test harness for patient interaction.

Loads the first case from test_output.json (generated by test_generation.py)
and runs a simulated attending encounter against it.

Run from the ERSim directory:
    python -m cases.test_interaction

You can also pass a case index:
    python -m cases.test_interaction --case 2
"""

import json
import sys
import argparse

from .schema import GeneratedCase
from .interaction import PatientSession


def run(case_index: int = 0, model: str = "anthropic/claude-haiku-4-5"):
    # Load case from last generation run
    try:
        with open("test_output.json") as f:
            data = json.load(f)
    except FileNotFoundError:
        print("No test_output.json found. Run test_generation first.")
        sys.exit(1)

    cases = data.get("cases", [])
    if case_index >= len(cases):
        print(f"Only {len(cases)} cases available. Using case 0.")
        case_index = 0

    case = GeneratedCase.model_validate(cases[case_index])
    pp = case.patient_profile
    pl = case.presenting_layer

    print(f"\n{'='*60}")
    print(f"CASE {case.case_id} — Acuity {pl.acuity.value}")
    print(f"{'='*60}")
    print(f"Triage note: {pl.triage_note}")
    print(f"\nHook (you don't see this in game): {case.narrative_hook}")
    print(f"True diagnosis (you don't see this): {case.medical_truth.true_diagnosis}")
    print(f"\nPatient: {pp.first_name} {pp.last_name}, {pl.age}{pl.sex}")
    print(f"{'='*60}\n")

    session = PatientSession(case, model=model)

    print("Starting interaction. You are the attending.")
    print("Commands:")
    print("  /test <name>   — order a test (e.g. /test troponin, /test EKG)")
    print("  /exam <name>   — perform physical exam (e.g. /exam abdomen, /exam murphy's sign)")
    print("  /family        — bring family member into room")
    print("  /chart         — show what has been revealed so far")
    print("  /quit          — end encounter\n")

    # Automated opening — attending walks in
    opening = "Hi, I'm Dr. [name]. What's going on today?"
    print(f"[YOU]: {opening}")
    response = session.interact(opening)
    print(f"[{pp.first_name.upper()}]: {response}\n")

    while True:
        try:
            raw = input("[YOU]: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n[Encounter ended]")
            break

        if not raw:
            continue

        # Normalize — strip leading slash so both '/exam' and 'exam' work
        raw_clean = raw.lstrip("/")

        if raw_clean.lower() == "quit":
            break

        elif raw_clean.lower().startswith("exam "):
            maneuver = raw_clean[5:].strip()
            result = session.examine(maneuver)
            print(f"\n{result}\n")

        elif raw_clean.lower().startswith("test "):
            test_name = raw_clean[5:].strip()
            result = session.order_test(test_name)
            print(f"\n{result}\n")

        elif raw_clean.lower() == "family":
            result = session.bring_family()
            print(f"\n{result}\n")
            # Patient reacts to family entering
            response = session.interact(
                "[Family member has entered the room]"
            )
            print(f"[{pp.first_name.upper()}]: {response}\n")

        elif raw_clean.lower() == "chart":
            summary = session.get_reveal_summary()
            print(f"\n--- CHART SUMMARY (turn {summary['turns']}) ---")
            print(f"Tests ordered: {', '.join(summary['tests_ordered']) or 'none'}")
            print(f"Family present: {summary['family_present']}")
            print(f"\nRevealed ({len(summary['revealed'])} nodes):")
            for r in summary["revealed"]:
                print(f"  [turn {r['turn']}] {r['information']}")
            print(f"\nStill locked ({len(summary['locked'])} nodes):")
            for l in summary["locked"]:
                print(f"  [{l['trigger_needed']}] needs: {l['trigger_detail']}")
            print()

        else:
            response = session.interact(raw)
            print(f"[{pp.first_name.upper()}]: {response}\n")

    # End of encounter summary
    print(f"\n{'='*60}")
    print("ENCOUNTER SUMMARY")
    print(f"{'='*60}")
    summary = session.get_reveal_summary()
    total = len(case.reveal_sequence)
    found = len(summary["revealed"])
    print(f"Turns: {summary['turns']}")
    print(f"Revealed: {found}/{total} nodes ({100*found//total if total else 0}%)")
    print(f"Tests ordered: {', '.join(summary['tests_ordered']) or 'none'}")
    print(f"\nTrue diagnosis: {case.medical_truth.true_diagnosis}")
    print(f"Classic miss: {case.medical_truth.classic_miss_reason}")
    print(f"Correct disposition: {case.outcome_trajectory.disposition}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--case", type=int, default=0,
                        help="Case index from test_output.json (default: 0)")
    parser.add_argument("--model", type=str,
                        default="anthropic/claude-haiku-4-5",
                        help="OpenRouter model ID")
    args = parser.parse_args()
    run(case_index=args.case, model=args.model)
